### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by MentalGear** [helixbass/vue-coffee-eslint-example#2]
I was really excited to find your coffescript packages!
Unfortunately, this example seems to error out. (unmodified example)

If it works for you, maybe you can help me figure it out ?

>  ERROR  Failed to compile with 1 errors
> 
>  error  in ./src/components/HelloWorld.vue
> 
> Module Error (from ./node_modules/eslint-loader/index.js):
> 
> /Users/[USER]/Downloads/vue-coffee-eslint-example-master/src/components/HelloWorld.vue
>   0:0  error  Parsing error: unexpected (
> 
> ✖ 1 problem (1 error, 0 warnings)
> 
> 
>  @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/App.vue?vue&type=script&lang=js& 8:0-53 12:16-26
>  @ ./src/App.vue?vue&type=script&lang=js&
>  @ ./src/App.vue
>  @ ./src/main.coffee
>  @ multi (webpack)-dev-server/client?http://192.168.178.68:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.coffee

**Comment by helixbass** [comment]
Ok so this is an error you got when running `yarn serve`?

Did you use `yarn` to install dependencies (rather than `npm`), ie `yarn install`?

**Comment by MentalGear** [comment]
I actually used npm, do your packages only work with yarn ?

**Comment by MentalGear** [comment]
Strange, seems to work with yarn, thanks for ya coffee packages ! 👍

**Comment by MentalGear** [comment]
Any idea why yarn makes such a big diff? Packages should be the same?

**Comment by helixbass** [comment]
Generally speaking you should be able to use `yarn` or `npm`

Here I'd guess `npm` wasn't handling the `github:` dependencies from `package.json` correctly (I've seen both `yarn` and `npm` mishandle Github dependencies in different ways...)

**Comment by MentalGear** [comment]
Thanks for the explication. Is there any specfic reason you use your own version of vue cli & parser ?

**Comment by helixbass** [comment]
Yes, see https://github.com/helixbass/eslint-plugin-coffee/issues/27 (I created this repo to help with that issue)

**Comment by MentalGear** [comment]
For documentation: npm probably didn't work since it doesn't handle "resolutions" of package.json, only yarn does. ( the custom modified resource defined in "resolutions" are needed for coffescript to get parsed by eslint )
